install work

diff --git a/bin/steps/swiftenv b/bin/steps/swiftenv
--- a/bin/steps/swiftenv
+++ b/bin/steps/swiftenv
@@ -11,6 +11,44 @@
 #   export SWIFT_VERSION="$DEFAULT_SWIFT_VERSION"
 # fi
 
-echo "installing ubuntu"
-curl -sL https://swift.vapor.sh/ubuntu | bash
-echo "done installing ubuntu"
+# echo "installing ubuntu"
+# curl -sL https://swift.vapor.sh/ubuntu | bash
+# echo "done installing ubuntu"
+
+echo "Swift 3 Quick Installer";
+
+# Determine OS
+UNAME=`uname`;
+if [[ $UNAME == "Linux" ]];
+then
+    UBUNTU_RELEASE=`lsb_release -a 2>/dev/null`;
+    if [[ $UBUNTU_RELEASE == *"14.04"* ]];
+    then
+        OS="ubuntu1404";
+        TC="swift-3.0-RELEASE-ubuntu14.04"
+    else
+        OS="ubuntu1510";
+        TC="swift-3.0-RELEASE-ubuntu15.10"
+    fi
+else
+    echo "❌  Unsupported Operating System: $UNAME";
+    exit 1;
+fi
+
+echo "🖥  Operating System: $OS";
+
+echo "⬇️  Downloading"
+wget https://swift.org/builds/swift-3.0-release/$OS/swift-3.0-RELEASE/$TC.tar.gz
+
+echo "🔧  Untarring"
+tar zxf $TC.tar.gz
+rm -rf $TC.tar.gz
+
+echo "🚀  Installing";
+echo "🔒  Sudo required";
+# mv $TC /swift-3.0
+
+echo "export PATH=/${TC}/usr/bin:\"\${PATH}\"" >> ~/.bashrc
+source ~/.bashrc
+
+echo "✅  Done";
